Q.1) Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np
arr = np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


Q.2) Accept two lists of 5 elements each from the user.

Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [2]:
import numpy as np
l1 = []
l2 = []

for i in range(5):
  x = int (input())
  l1.append(x)

print("\n")

for i in range(5):
  x = int (input())
  l2.append(x)

array1 = np.array(l1)
array2 = np.array(l2)


#Concatenate arrays
array_con = np.concatenate((array1, array2))
print("\nConcatenated Array :")
print(array_con)

#Sort arrays
print("\n Sorted Array1 :")
print(np.sort(l1))
print("\nSorted Array2 :")
print(np.sort(l2))
print("\nSorted Concatenated Array :")
print(np.sort(array_con))

15
45
20
10
9


56
48
12
84
98

Concatenated Array :
[15 45 20 10  9 56 48 12 84 98]

 Sorted Array1 :
[ 9 10 15 20 45]

Sorted Array2 :
[12 48 56 84 98]

Sorted Concatenated Array :
[ 9 10 12 15 20 45 48 56 84 98]


Q.3) Write a code snippet to find the dimensions of a ndarray and its size.

In [3]:
import numpy as np

arr = np.array([[2,2,4],[4,5,6],[1,2,5],[3,2,1]])
print("Array :")
print(arr)

print("Dimention of Array :")
print("Size of", arr.shape,"array :", arr.size)

Array :
[[2 2 4]
 [4 5 6]
 [1 2 5]
 [3 2 1]]
Dimention of Array :
Size of (4, 3) array : 12


Q.4) How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet

Hint: np.newaxis, np.expand_dims

In [4]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9])
print("1-D Array :")
print(arr)

print("Dimension of 1-D array :")
print(arr.shape)

print("\nNew dimension of 2-D array (using newaxis) :")
arr1 = arr[np.newaxis,:]
print(arr1.shape)

print("\nNew dimension of 2-D array (using newaxis) :")
arr1 = arr[:,np.newaxis]
print(arr1.shape)

print("\nNew dimension of 2-D array (using expand_dims):")
arr2 = np.expand_dims(arr, axis=1)
print(arr2.shape)

print("\nNew dimension of 2-D array (using expand_dims) :")
arr2 = np.expand_dims(arr, axis=0)
print(arr2.shape)

1-D Array :
[1 2 3 4 5 6 7 8 9]
Dimension of 1-D array :
(9,)

New dimension of 2-D array (using newaxis) :
(1, 9)

New dimension of 2-D array (using newaxis) :
(9, 1)

New dimension of 2-D array (using expand_dims):
(9, 1)

New dimension of 2-D array (using expand_dims) :
(1, 9)


Q.5) Consider two square numpy arrays. Stack them vertically and horizontally.

Hint: Use vstack(), hstack()

In [5]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr2 = np.array([9,8,7,6,5,4,3,2,1])

print("Vertically Stacked Array :")
print(np.vstack((arr1, arr2)))

print("\nHorizontally Stacked Array :")
print(np.hstack((arr1, arr2)))

Vertically Stacked Array :
[[1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1]]

Horizontally Stacked Array :
[1 2 3 4 5 6 7 8 9 9 8 7 6 5 4 3 2 1]


Q.6) How to get unique items and counts of unique items?

In [6]:
import numpy as np

arr = np.array([1,2,3,2,2,1,5,4,6])

unique_ele, count_ele= np.unique(arr, return_counts = True)

ele_count = np.asarray((unique_ele, count_ele)).T
print(ele_count)

[[1 2]
 [2 3]
 [3 1]
 [4 1]
 [5 1]
 [6 1]]
